//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reserveID { get; set; }
        public string Reservation_Number { get; set; }
        public string byName { get; set; }
        public string byEmail { get; set; }
        public string byContact { get; set; }
        public Nullable<int> numberOfPersons { get; set; }
        public string reserveDateTime { get; set; }
        public string eventType { get; set; }
        public string byMessage { get; set; }
    }
}
