//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMessage
    {
        public int msgID { get; set; }
        public string msgName { get; set; }
        public string msgEmail { get; set; }
        public string msgSubject { get; set; }
        public string msgBody { get; set; }
    }
}
